# Generated by Django 4.1 on 2023-07-27 00:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('picture', models.ImageField(upload_to='PatientPics')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('disease', models.CharField(max_length=250)),
                ('advice', models.TextField()),
                ('medicine', models.CharField(max_length=250)),
                ('tests', models.CharField(max_length=250)),
                ('follow_up', models.DateField(default=datetime.datetime(2023, 8, 26, 5, 41, 28, 967733))),
                ('charges', models.IntegerField()),
                ('report', models.FileField(default='new.txt', upload_to='')),
                ('report_ready', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.modelpatient')),
            ],
        ),
    ]
